points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        pinky2:
        pinky:
        ring:
          key.splay: -3
          key.origin: [-12, -19]
          key.stagger: 8
        middle:
          key.splay: -3
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: -2
        inner2:
          key.spread: 21
          key.stagger: 15
          rows.home.skip: true
          rows.top.skip: true
          rows.upper.skip: true
      rows:
        bottom:
        home:
        top:
        upper:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-20, -23]
      columns:
        nearer:
          rows.thumb.skip: true
          key.spread: 2
        near:
          key.spread: 
          rows.thumb.skip: true
        home:
          rows.thumb.skip: true
          key.spread: 21.28
          key.splay: -20
          key.origin: [-11.75, -8]
          key.shift: [0, 10]
          key.height: 1.5 * U
        far:
          key.spread: 21.25
          key.splay: -0
          key.origin: [-9.5, -9]
      rows:
        thumb2:
        thumb:
  rotate: -10
  mirror:
    ref: thumbfan_far_thumb
    distance: 50
outlines:
  board_left:
    - where: /^matrix_.*/
      what: rectangle
      size: [U + 3, U + 3]
      fillet: 3
    - where: thumbfan_home_thumb2
      what: rectangle
      size: [U + 30, U + 25]
      fillet: 3
    - where: thumbfan_nearer_thumb2
      what: rectangle
      size: [U + 3, U + 5]
      fillet: 3
    - where: thumbfan_near_thumb2
      what: rectangle
      size: [U + 20, U + 5]
      fillet: 3
    - where: thumbfan_far_thumb2
      what: rectangle
      size: [U + 5, U + 5]
      fillet: 3
    - where: thumbfan_far_thumb
      what: rectangle
      size: [U + 5, U + 7]
      fillet: 3
    - where: matrix_ring_upper
      what: rectangle
      size: [U + 5, U + 3]
      fillet: 3
    - where: matrix_ring_top
      what: rectangle
      size: [U + 5, U + 10]
      fillet: 3
    - where: matrix_ring_upper
      what: rectangle
      size: [U + 5, U + 5]
      fillet: 3
    - where: matrix_inner_top
      what: rectangle
      size: [U + 60, U + 10]
      fillet: 3
    - where: matrix_inner_upper
      what: rectangle
      size: [U + 60, U + 7]
      fillet: 3
    - where: matrix_inner2_bottom
      what: rectangle
      size: [U + 18, U + 15]
      fillet: 3
    - where: matrix_middle_bottom
      what: rectangle
      size: [U + 18, U + 10]
      fillet: 3
    - where: matrix_middle_upper
      what: rectangle
      size: [U + 2, U + 0]
      fillet: 3
    - where: matrix_inner_bottom
      what: rectangle
      size: [U + 43, U + 20]
      fillet: 3
    - where: matrix_pinky2_upper
      what: rectangle
      size: [U + 3, U + 3]
      fillet: 1
  board_right:
    - where: /^mirror_matrix_.*/
      what: rectangle
      size: [U + 3, U + 3]
      fillet: 3
    - where: mirror_thumbfan_home_thumb2
      what: rectangle
      size: [U + 30, U + 25]
      fillet: 3
    - where: mirror_thumbfan_nearer_thumb2
      what: rectangle
      size: [U + 3, U + 5]
      fillet: 3
    - where: mirror_thumbfan_near_thumb2
      what: rectangle
      size: [U + 20, U + 5]
      fillet: 3
    - where: mirror_thumbfan_far_thumb2
      what: rectangle
      size: [U + 5, U + 5]
      fillet: 3
    - where: mirror_thumbfan_far_thumb
      what: rectangle
      size: [U + 5, U + 7]
      fillet: 3
    - where: mirror_matrix_ring_upper
      what: rectangle
      size: [U + 5, U + 3]
      fillet: 3
    - where: mirror_matrix_ring_top
      what: rectangle
      size: [U + 5, U + 3]
      fillet: 3
    - where: mirror_matrix_inner_top
      what: rectangle
      size: [U + 60, U + 10]
      fillet: 3
    - where: mirror_matrix_inner_upper
      what: rectangle
      size: [U + 60, U + 7]
      fillet: 3
    - where: mirror_matrix_inner2_bottom
      what: rectangle
      size: [U + 18, U + 15]
      fillet: 3
    - where: mirror_matrix_middle_bottom
      what: rectangle
      size: [U + 18, U + 10]
      fillet: 3
    - where: mirror_matrix_inner_bottom
      what: rectangle
      size: [U + 43, U + 20]
      fillet: 3
    - where: mirror_matrix_pinky2_upper
      what: rectangle
      size: [U + 3, U + 3]
      fillet: 1
    - where: mirror_matrix_pinky_upper
      what: rectangle
      size: [U + 5, U + 3]
      fillet: 1
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      hotswap:
        what: mx
        where: /^((matrix_)|(thumbfan_)).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_main:
        what: diode
        where: /^((matrix_)|(thumbfan_)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [22,12]
          rotate: -90
      oled:
        what: oled
        params:
          side: "F"
          SDA: P2
          SCL: P3
        where:
          ref: matrix_inner_top
          shift: [16,-8]
          rotate: 90
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      hotswap:
        what: mx
        where: /^((mirror_matrix_)|(mirror_thumbfan_)).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_main:
        what: diode
        where: /^((mirror_matrix_)|(mirror_thumbfan_)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: mirror_matrix_inner_top
          shift: [22,12]
          rotate: 90
      oled:
        what: oled
        params:
          side: "F"
          SDA: P2
          SCL: P3
        where:
          ref: mirror_matrix_inner_top
          shift: [28,-8]
          rotate: -90